services:
  postgres:
    image: postgres:16
    container_name: runsight-postgres
    restart: unless-stopped
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: runsight-backend
    env_file:
      - .env
    depends_on:
      - postgres
    ports:
      - "8080:8080"

volumes:
  postgres_data:
