name: Deploy to GCP

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.GCP_SSH_KEY }}

      - name: Deploy to GCP VM
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.GCP_USER }}@${{ secrets.GCP_HOST }} << 'EOF'
            set -e

            cd ~/apps/runsight-backend

            echo "🔄 Pulling latest code..."
            git fetch origin main
            git reset --hard origin/main

            echo "📦 Rebuilding Docker containers..."
            sudo docker-compose down
            sudo docker-compose up -d --build

            echo "✅ Deployment completed successfully!"
          EOF